server:
  port: 8084
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.211.132
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
