server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou2?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.211.132
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
#    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
#    instance-id: ${spring.application.name}:${server.port}
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.
logging:
  level:
    com.leyou: debug